version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: npm run start:dev
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env